### ISSUE TITLE
"select 1"  command cannot be used.

### ISSUE THREAD

**Issue by canddyBrea** [Kuari/MyRedisDesktopManager#1]
new data list not show in left.

**Comment by hunter-ji** [comment]
> new data list not show in left.

Thank you for your feedback!

I understand what you mean. First of all, it should be a cache problem that the db is not updated in time, and I will pay attention to it. The second is that "select 1" has no effect because I deliberately set it, because the command itself is under a certain db, so the commands across db are limited.

Do you feel the need to execute commands across db? If there is, I will seriously consider this requirement.
